In [1]:
import numpy as np
import scipy
from scipy import stats
from astropy.io import fits
north_list = fits.open('goodsn_3dhst.v4.1.cat.FITS', memmap=True)
north_data = north_list[1].data
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
pha_list = fits.open('3dhst.v4.1.4.full.v1.fits', memmap=True)
pha_data = pha_list[1].data
import numpy.ma as ma

def magab_err(flux, error):
    if (np.absolute(error)) >= flux:
        return 1.085
    else:
        return np.absolute((-1.085)* (error/flux))
    
def magab(flux, error):
    if error > flux:
        return (((-2.5)*(np.log10(error))) + 25 )
    else:
        return (((-2.5)*(np.log10(flux))) + 25 )

magfunc = np.vectorize(magab)
magerrorfunc = np.vectorize(magab_err)

In [2]:
print scipy.stats.itemfreq(pha_data['id'][75079:113358] == north_data['id'])
north_phot_use_1= (north_data['use_phot']==1)
print scipy.stats.itemfreq((north_data['use_phot']==1))

[[    1 38279]]
[[    0  5778]
 [    1 32501]]


In [3]:
def cutter (a, a_err, b, b_err, c, c_err): 
    return (((magfunc(a, a_err)- magfunc(b, b_err) >(0.44 + (((magerrorfunc(a, a_err))**2) + ((magerrorfunc(b, b_err))**2))**.5)) & 
(magfunc(c, c_err)- magfunc(b, b_err) >(0.44 + (((magerrorfunc(c, c_err))**2) + ((magerrorfunc(b, b_err))**2))**.5))) & north_phot_use_1 & ((a>=0)& (b>=0) & (c>=0)) & (((a/a_err)>3)&((b/b_err)>3)&((c/c_err)>3)))
#& (((a/a_err)>3)&((b/b_err)>3)&((c/c_err)>3))

In [4]:
###jhk selection###
afils = [north_data['f_f125w'],north_data['e_f125w'],north_data['f_j'], north_data['e_j']]
bfils= [north_data['f_f160w'], north_data['e_f160w'], north_data['f_h'], north_data['e_h']]
cfils= [north_data['f_ks'], north_data['e_ks']]

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,1):
            globals()['north_jhk%d%d%d' %(a,b,c)] = (cutter(afils[2*a], afils[1+(2*a)], bfils[2*b], bfils[1+(2*b)], cfils[2*c], cfils[1+(2*c)]))

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,1):
            print "north_jhk%d%d%d"%(a,b,c), np.count_nonzero((globals()['north_jhk%d%d%d' %(a,b,c)])==1)

C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()


north_jhk000 6
north_jhk010 47
north_jhk100 5
north_jhk110 27


C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:22: RuntimeWarning: invalid value encountered in log10


In [5]:
print north_data['id'][north_jhk000]

[ 4732  5883  7721 11360 23540 34719]


In [6]:
###ijh selection###
bfils = [north_data['f_f125w'],north_data['e_f125w'],north_data['f_j'], north_data['e_j']]
cfils= [north_data['f_f160w'], north_data['e_f160w'], north_data['f_h'], north_data['e_h']]
afils= [north_data['f_i'], north_data['e_i'], north_data['f_F775W'], north_data['e_F775W']]

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,2):
            globals()['north_ijh%d%d%d' %(a,b,c)] = (cutter(afils[2*a], afils[1+(2*a)], bfils[2*b], bfils[1+(2*b)], cfils[2*c], cfils[1+(2*c)]))

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,2):
            print "north_ijh%d%d%d"%(a,b,c), np.count_nonzero((globals()['north_ijh%d%d%d' %(a,b,c)])==1)

C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:22: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()


north_ijh000 38
north_ijh001 4
north_ijh010 77
north_ijh011 7
north_ijh100 63
north_ijh101 4
north_ijh110 230
north_ijh111 6


In [7]:
print north_data['id'][north_ijh000 | north_ijh001]

[  595  2667  3315  3831  4013  4022  4259  5687  6459  7300 10639 13728
 13876 13998 15722 16597 18360 18865 19150 19388 19406 22638 24346 24427
 24524 24621 26710 27302 28478 28615 28620 29185 29570 29675 34179 35075
 35396 36852 36886]


In [8]:
###vz jhk selection###
bfils = [north_data['f_z'],north_data['e_z'],north_data['f_F850LP'], north_data['e_F850LP']]
cfils= [north_data['f_f125w'],north_data['e_f125w'],north_data['f_j'], north_data['e_j'], north_data['f_f140w'], north_data['e_f140w'],north_data['f_f160w'], north_data['e_f160w'], north_data['f_h'], north_data['e_h']]
afils= [north_data['f_v'], north_data['e_v'], north_data['f_F606W'], north_data['e_F606W']]

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,5):
            globals()['north_vz%d%d%d' %(a,b,c)] = (cutter(afils[2*a], afils[1+(2*a)], bfils[2*b], bfils[1+(2*b)], cfils[2*c], cfils[1+(2*c)]))

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,5):
            print "north_vz%d%d%d"%(a,b,c), np.count_nonzero((globals()['north_vz%d%d%d' %(a,b,c)])==1)

C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:22: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()


north_vz000 266
north_vz001 16
north_vz002 49
north_vz003 213
north_vz004 10
north_vz010 26
north_vz011 5
north_vz012 11
north_vz013 37
north_vz014 4
north_vz100 347
north_vz101 16
north_vz102 57
north_vz103 264
north_vz104 10
north_vz110 21
north_vz111 5
north_vz112 9
north_vz113 39
north_vz114 4


In [12]:
print north_data['id'][north_vz110|north_vz112|north_vz113]

[ 1928  3646  3715  4259  4393  4650  5080  6373  6459  7089  7817  9189
  9296 12014 12769 14392 16009 16651 19405 19603 19748 20585 23343 23492
 23685 24121 24964 25196 26011 26804 27161 27884 28439 29329 29828 31075
 32166 33408 34570 36769 37665]


In [13]:
###vij selection###
cfils = [north_data['f_f125w'],north_data['e_f125w'],north_data['f_j'], north_data['e_j']]
bfils= [north_data['f_i'], north_data['e_i'], north_data['f_F775W'], north_data['e_F775W']]
afils= [north_data['f_v'], north_data['e_v'], north_data['f_F606W'], north_data['e_F606W']]

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,2):
            globals()['north_vij%d%d%d' %(a,b,c)] = (cutter(afils[2*a], afils[1+(2*a)], bfils[2*b], bfils[1+(2*b)], cfils[2*c], cfils[1+(2*c)]))

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,2):
            print "north_vij%d%d%d"%(a,b,c), np.count_nonzero((globals()['north_vij%d%d%d' %(a,b,c)])==1)

C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:22: RuntimeWarning: invalid value encountered in log10


north_vij000 103
north_vij001 2
north_vij010 22
north_vij011 8
north_vij100 170
north_vij101 2
north_vij110 17
north_vij111 6


C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()


In [14]:
print north_data['id'][north_vij110]

[  320  1955  6694  8380 10347 13114 15232 17121 18230 18613 19182 21776
 22717 24411 26451 33957 36716]


In [15]:
###ihk selection###
bfils = [north_data['f_f160w'], north_data['e_f160w'], north_data['f_h'], north_data['e_h']]
cfils= [north_data['f_ks'], north_data['e_ks']]
afils= [north_data['f_i'], north_data['e_i'], north_data['f_F775W'], north_data['e_F775W']]

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,1):
            globals()['north_ihk%d%d%d' %(a,b,c)] = (cutter(afils[2*a], afils[1+(2*a)], bfils[2*b], bfils[1+(2*b)], cfils[2*c], cfils[1+(2*c)]))

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,1):
            print "north_ihk%d%d%d"%(a,b,c), np.count_nonzero((globals()['north_ihk%d%d%d' %(a,b,c)])==1)

C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:22: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()


north_ihk000 12
north_ihk010 45
north_ihk100 12
north_ihk110 58


In [18]:
print north_data['id'][north_ihk100|north_ihk000]

[  903  4732  5883  7585  7721 11360 13789 23540 26328 27635 34719 35957]
