In [1]:
import numpy as np
import scipy
from scipy import stats
from astropy.io import fits
uds_list = fits.open('uds_3dhst.v4.2.cat.FITS', memmap=True)
uds_data = uds_list[1].data
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
pha_list = fits.open('3dhst.v4.1.4.full.v1.fits', memmap=True)
pha_data = pha_list[1].data
import numpy.ma as ma

def magab_err(flux, error):
    if (np.absolute(error)) >= flux:
        return 1.085
    else:
        return np.absolute((-1.085)* (error/flux))
    
def magab(flux, error):
    if error > flux:
        return (((-2.5)*(np.log10(error))) + 25 )
    else:
        return (((-2.5)*(np.log10(flux))) + 25 )

magfunc = np.vectorize(magab)
magerrorfunc = np.vectorize(magab_err)

In [3]:
print scipy.stats.itemfreq(pha_data['id'][163865:207967] == uds_data['id'])
uds_phot_use_1= (uds_data['use_phot']==1)
print scipy.stats.itemfreq((uds_data['use_phot']==1))

[[    1 44102]]
[[    0  7991]
 [    1 36111]]


In [4]:
def cutter (a, a_err, b, b_err, c, c_err): 
    return (((magfunc(a, a_err)- magfunc(b, b_err) >(0.44 + (((magerrorfunc(a, a_err))**2) + ((magerrorfunc(b, b_err))**2))**.5)) & 
(magfunc(c, c_err)- magfunc(b, b_err) >(0.44 + (((magerrorfunc(c, c_err))**2) + ((magerrorfunc(b, b_err))**2))**.5))) & uds_phot_use_1 & ((a>=0)& (b>=0) & (c>=0)) & (((a/a_err)>3)&((b/b_err)>3)&((c/c_err)>3)))
#& (((a/a_err)>3)&((b/b_err)>3)&((c/c_err)>3))

In [5]:
###jhk selection###
afils = [uds_data['f_f125w'],uds_data['e_f125w'], uds_data['f_j'], uds_data['e_j']]
bfils= [uds_data['f_h'], uds_data['e_h'], uds_data['f_f160w'], uds_data['e_f160w']]
cfils= [uds_data['f_k'], uds_data['e_k']]

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,1):
            globals()['uds_jhk%d%d%d' %(a,b,c)] = (cutter(afils[2*a], afils[1+(2*a)], bfils[2*b], bfils[1+(2*b)], cfils[2*c], cfils[1+(2*c)]))

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,1):
            print "uds_jhk%d%d%d"%(a,b,c), np.count_nonzero((globals()['uds_jhk%d%d%d' %(a,b,c)])==1)

C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:22: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: divide by zero encountered in divide
  app.launch_new_instance()
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: divide by zero encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in divide
  app.launch_new_instance()


uds_jhk000 48
uds_jhk010 16
uds_jhk100 29
uds_jhk110 19


In [7]:
print (uds_data['id'][uds_jhk010])

[   70   411  5178 12628 15589 18097 23793 25635 29817 30396 30800 32883
 34360 38344 41342 43637]


In [9]:
###ijh selection###
bfils = [uds_data['f_f125w'],uds_data['e_f125w'], uds_data['f_j'], uds_data['e_j'] ]
cfils= [uds_data['f_h'], uds_data['e_h'],uds_data['f_f160w'], uds_data['e_f160w']]
afils= [uds_data['f_I'], uds_data['e_I'], uds_data['f_f814W'], uds_data['e_f814W']]

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,2):
            globals()['uds_ijh%d%d%d' %(a,b,c)] = (cutter(afils[2*a], afils[1+(2*a)], bfils[2*b], bfils[1+(2*b)], cfils[2*c], cfils[1+(2*c)]))

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,2):
            print "uds_ijh%d%d%d"%(a,b,c), np.count_nonzero((globals()['uds_ijh%d%d%d' %(a,b,c)])==1)

C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:22: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: divide by zero encountered in divide
  app.launch_new_instance()
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: divide by zero encountered in log10


uds_ijh000 3
uds_ijh001 60
uds_ijh010 10
uds_ijh011 301
uds_ijh100 0
uds_ijh101 50
uds_ijh110 9
uds_ijh111 256


C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in divide
  app.launch_new_instance()


In [12]:
###ihk selection###
bfils = [uds_data['f_h'], uds_data['e_h'],uds_data['f_f160w'], uds_data['e_f160w']]
cfils = [uds_data['f_k'], uds_data['e_k']]
afils= [uds_data['f_I'], uds_data['e_I'], uds_data['f_f814W'], uds_data['e_f814W']]

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,1):
            globals()['uds_ihk%d%d%d' %(a,b,c)] = (cutter(afils[2*a], afils[1+(2*a)], bfils[2*b], bfils[1+(2*b)], cfils[2*c], cfils[1+(2*c)]))

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,1):
            print "uds_ihk%d%d%d"%(a,b,c), np.count_nonzero((globals()['uds_ihk%d%d%d' %(a,b,c)])==1)

C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:22: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()


 uds_ihk000 63
uds_ihk010 34
uds_ihk100 42
uds_ihk110 25


C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: divide by zero encountered in divide
  app.launch_new_instance()


In [13]:
print (uds_data['id'][uds_ihk110])

[   70   411  5178  9055 12299 12628 16744 17322 18097 20779 20919 23793
 23919 25215 25635 26435 27556 30800 32883 34360 38344 39944 41342 42751
 43637]


In [14]:
###vij selection###
cfils = [uds_data['f_f125w'],uds_data['e_f125w'], uds_data['f_j'], uds_data['e_j'] ]
bfils= [uds_data['f_I'], uds_data['e_I'], uds_data['f_f814W'], uds_data['e_f814W']]
afils= [uds_data['f_v'], uds_data['e_v'], uds_data['f_f606w'], uds_data['e_f606w']]

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,2):
            globals()['uds_vij%d%d%d' %(a,b,c)] = (cutter(afils[2*a], afils[1+(2*a)], bfils[2*b], bfils[1+(2*b)], cfils[2*c], cfils[1+(2*c)]))

for a in range(0,2):
    for b in range (0,2):
        for c in range (0,2):
            print "uds_vij%d%d%d"%(a,b,c), np.count_nonzero((globals()['uds_vij%d%d%d' %(a,b,c)])==1)

C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:22: RuntimeWarning: invalid value encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:24: RuntimeWarning: divide by zero encountered in log10
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in greater
  app.launch_new_instance()


uds_vij000 25
uds_vij001 12
uds_vij010 5
uds_vij011 10
uds_vij100 23
uds_vij101 8
uds_vij110 4
uds_vij111 8


C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: invalid value encountered in divide
  app.launch_new_instance()
C:\Anaconda\lib\site-packages\IPython\kernel\__main__.py:3: RuntimeWarning: divide by zero encountered in divide
  app.launch_new_instance()


In [15]:
print (uds_data['id'][uds_vij110])

[14478 17317 21730 21920]
